name: nix-build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-push-oci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-23.11
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - name:  build sppl
      run: |
        nix build \
          -L \
          -o ./sppl \
          '.#sppl'
    - name:  build base image (not pushed)
      run: |
        nix build \
          -L \
          -o ./imgBase \
          '.#ociImgBase'
    - name:  build Gensql Query image
      run: |
        nix build \
          -L \
          -o ./imgGensqlQuery \
          '.#ociImgGensqlQuery'
    - name:  build Loom image
      run: |
        nix build \
          -L \
          -o ./imgLoom \
          '.#ociImgLoom'

    - name: Login to Docker Hub
      # only run this  when running on main, because
      # that is the only  time we need these creds;
      # otherwise, Fork-based PRs cannot succeed
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: push gensql query
      if: github.ref == 'refs/heads/main'
      run: |
        docker load -i ./imgGensqlQuery
        docker push --all-tags probcomp/gensql.query
    - name: push loom
      if: github.ref == 'refs/heads/main'
      run: |
        docker load -i ./imgLoom
        docker push --all-tags probcomp/inferenceql.loom
